name: Verade-Build
version: 42
main: net.verade.Build
author: piajesse
depend: [EssentialsV]
commands:
  website:
    description:
    aliases:
  discord:
    description:
    aliases:
  pl:
    description:
    aliases:
