name: TLBuild
version: 1.0
main: net.timelegacy.tlbuild.TLBuild
author: piajesse, Nyarrth
api-version: 1.13
depend: [TLCore, PlotSquared]
commands:
  review:
    description: Review plots!
  plotalias:
    description: Set the name of your plot.
  submitplot:
    description: Submit your plot review.
  unsubmitplot:
    description: Unsubmit your plot for review.
  forums:
    description: Forums Link.
  setlevel:
    description: Set your creative level.
  getlevel:
    description: Show your creative level.
  levelperks:
    description: Show your level perks.